name = "nibe-settings-gateway"
main = "worker.js"
compatibility_date = "2026-09-28"
workers_dev = true

[vars]
GITHUB_REPOSITORY = "mrobaczyk/nibe"
GITHUB_WORKFLOW = "nibe_set_parameters.yml"
GITHUB_REF = "main"
ALLOWED_ORIGIN = "https://mrobaczyk.github.io"
