name: Manual Nibe Stats Check

on:
  workflow_dispatch: # To pozwala na ręczne kliknięcie "Run workflow"

jobs:
  debug-nibe-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Execute check_stats.py
        env:
          NIBE_CLIENT_ID: ${{ secrets.NIBE_CLIENT_ID }}
          NIBE_CLIENT_SECRET: ${{ secrets.NIBE_CLIENT_SECRET }}
        run: python check_stats.py
